package org.ghostcloak.app.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.text.style.TextOverflow
import java.time.*
import java.time.format.DateTimeFormatter
import org.ghostcloak.app.application.AppState
import org.ghostcloak.app.ui.components.*
import org.ghostcloak.identity.*
import org.ghostcloak.messaging.*
import org.ghostcloak.protocol.EnvelopeCodec

@Composable fun ConversationScreen(state: AppState, status: ContactStatus, back: () -> Unit,
    security: () -> Unit, send: (String, () -> Unit) -> Unit, delete: (String) -> Unit, connect: () -> Unit = {}, sync: () -> Unit = {}, accept: () -> Unit = {}, reject: () -> Unit = {}) {
    var draft by remember(status.contact.remoteDeviceId) { mutableStateOf("") }
    var rejectedPaste by remember { mutableStateOf(false) }
    var actions by remember { mutableStateOf(false) }
    var deleting by remember { mutableStateOf<String?>(null) }
    val size = remember(draft) { val bytes = draft.encodeToByteArray(); try { bytes.size } finally { bytes.fill(0) } }
    val changed = status.identity?.trustState == IdentityTrustState.CHANGED
    val active = status.session == SessionLifecycle.ACTIVE && !changed && !status.contact.blocked && !status.contact.request
    val list = rememberLazyListState()
    LaunchedEffect(state.messages.size) { if (state.messages.isNotEmpty()) list.animateScrollToItem(state.messages.lastIndex) }
    Column(Modifier.fillMaxSize().imePadding()) {
        Surface(color=MaterialTheme.colorScheme.surface) { Row(Modifier.fillMaxWidth().padding(horizontal = 8.dp, vertical = 8.dp), verticalAlignment = Alignment.CenterVertically) {
            IconButton(onClick = back) { AppIcon(Glyph.BACK, "Back") }
            Avatar(status.contact.displayName, Modifier.size(40.dp))
            Column(Modifier.weight(1f).padding(horizontal = 8.dp)) {
                Text(status.contact.displayName, style = MaterialTheme.typography.titleMedium, maxLines=1, overflow=TextOverflow.Ellipsis)
                Text(when { status.contact.blocked -> "Blocked on this device"; changed -> "! Security identity changed"; status.contact.request -> "Message request - Unverified"; !active -> "Session unavailable";
                    status.identity?.trustState == IdentityTrustState.VERIFIED -> "Encrypted · Verified"; else -> "Encrypted · Unverified" },
                    style = MaterialTheme.typography.bodyMedium, color = if (changed) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.onSurfaceVariant)
            }
            IconButton(onClick = security) { AppIcon(Glyph.SHIELD, "Security") }
            if(state.networkConfigured && !state.demo) Box {
                IconButton(onClick={actions=true}) { AppIcon(Glyph.MORE,"Conversation options") }
                DropdownMenu(expanded=actions,onDismissRequest={actions=false}) {
                    DropdownMenuItem(text={Text("Sync")},onClick={actions=false;sync()})
                }
            }
        }
        }
        if(!state.networkConnected) Box(Modifier.padding(horizontal = 16.dp)) { NetworkActions(state, connect, sync) }
        HorizontalDivider()
        if (state.demo) Text("LOCAL SIMULATOR · Replies are generated by the debug endpoint", Modifier.padding(16.dp),
            style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.primary)
        if (changed) TextButton(onClick = security, modifier = Modifier.fillMaxWidth()) { Text("! Review changed identity before sending", color = MaterialTheme.colorScheme.error) }
        LazyColumn(Modifier.weight(1f).fillMaxWidth(), state = list, contentPadding = PaddingValues(20.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            if (state.messages.isEmpty()) item { InfoPanel("A conversation starts here", if (state.networkConfigured && !state.demo) "End-to-end encrypted. Messages arrive automatically while Ghost Cloak is open." else "Messages are encrypted before local transport. This prototype cannot deliver to another device over a network.") }
            itemsIndexed(state.messages, key = { _, message -> message.localId }) { index, message ->
                val date = Instant.ofEpochMilli(message.timestamp).atZone(ZoneId.systemDefault()).toLocalDate()
                val previous = state.messages.getOrNull(index-1)?.let { Instant.ofEpochMilli(it.timestamp).atZone(ZoneId.systemDefault()).toLocalDate() }
                Column(verticalArrangement=Arrangement.spacedBy(12.dp)) {
                    if(date!=previous) Box(Modifier.fillMaxWidth().padding(vertical=12.dp),contentAlignment=Alignment.Center) {
                        Surface(shape=RoundedCornerShape(12.dp),color=MaterialTheme.colorScheme.surface) {
                            Text(when(date) {LocalDate.now()->"Today"; LocalDate.now().minusDays(1)->"Yesterday"; else->date.format(DateTimeFormatter.ofPattern("MMM d, yyyy"))},
                                Modifier.padding(horizontal=12.dp,vertical=5.dp),style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant)
                        }
                    }
                    MessageBubble(message,onDelete={deleting=message.localId})
                }
            }
        }
        if (status.contact.request && !status.contact.blocked) {
            Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("Accept this conversation?", style = MaterialTheme.typography.titleMedium)
                Text("This sender is not in your contacts. Accepting lets you reply; it does not verify their identity.", style = MaterialTheme.typography.bodyMedium)
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    Button(onClick = accept, enabled = !state.loading) { Text("Accept") }
                    TextButton(onClick = reject, enabled = !state.loading) { Text("Block & delete") }
                }
            }
        }
        Surface(color=MaterialTheme.colorScheme.surface) { Column(Modifier.padding(horizontal = 16.dp, vertical=10.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            ErrorNotice(state.error)
            if (size > EnvelopeCodec.MAX_BODY || rejectedPaste) Text("Too large. Maximum 16,384 UTF-8 bytes; text was not sent.", color = MaterialTheme.colorScheme.error)
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                OutlinedTextField(draft, onValueChange = { rejectedPaste = it.length > 65536; if (!rejectedPaste) draft = it },
                    enabled = active && !state.loading, modifier = Modifier.weight(1f), placeholder = { Text("Write a message…") }, maxLines = 5,
                    colors=OutlinedTextFieldDefaults.colors(unfocusedBorderColor=androidx.compose.ui.graphics.Color.Transparent,unfocusedContainerColor=MaterialTheme.colorScheme.surface,focusedContainerColor=MaterialTheme.colorScheme.surface),
                    shape = RoundedCornerShape(24.dp), isError = size > EnvelopeCodec.MAX_BODY)
                FilledIconButton(onClick = { send(draft) { draft = "" } }, enabled = active && !state.loading && draft.isNotBlank() && size <= EnvelopeCodec.MAX_BODY && !rejectedPaste,
                    modifier = Modifier.size(52.dp)) { AppIcon(Glyph.SEND,"Send") }
            }
            Text(if (size > 14000) "$size / 16,384 bytes" else "End-to-end encrypted", Modifier.padding(start = 10.dp, bottom = 12.dp), style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
    }
    }
    deleting?.let { id -> AlertDialog(onDismissRequest = { deleting = null }, title = { Text("Delete from this device?") },
        text = { Text("The other endpoint keeps its copy. Erasure from backups, memory or flash remnants is not guaranteed.") },
        confirmButton = { TextButton(onClick = { deleting = null; delete(id) }) { Text("Delete locally") } },
        dismissButton = { TextButton(onClick = { deleting = null }) { Text("Cancel") } }) }
}
