package org.ghostcloak.app.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import org.ghostcloak.app.ui.theme.GhostDimensions
import androidx.compose.ui.text.style.TextOverflow
import java.time.*
import java.time.format.DateTimeFormatter
import org.ghostcloak.app.application.AppState
import org.ghostcloak.app.ui.theme.GhostLayout
import org.ghostcloak.app.ui.components.*
import org.ghostcloak.identity.*
import org.ghostcloak.messaging.*
import org.ghostcloak.protocol.EnvelopeCodec

@Composable fun ConversationScreen(state: AppState, status: ContactStatus, back: () -> Unit,
    security: () -> Unit, send: (String, () -> Unit) -> Unit, delete: (String) -> Unit, connect: () -> Unit = {}, sync: () -> Unit = {}, accept: () -> Unit = {}, reject: () -> Unit = {}, clear: () -> Unit = {}, disappearing: (Int) -> Unit = {}, refresh: () -> Unit = {}) {
    var draft by remember(status.contact.remoteDeviceId) { mutableStateOf("") }
    var rejectedPaste by remember { mutableStateOf(false) }
    var actions by remember { mutableStateOf(false) }
    var deleting by remember { mutableStateOf<String?>(null) }
    var clearing by remember { mutableStateOf(false) }
    var timerSelector by remember { mutableStateOf(false) }
    val size = remember(draft) { val bytes = draft.encodeToByteArray(); try { bytes.size } finally { bytes.fill(0) } }
    val changed = status.identity?.trustState == IdentityTrustState.CHANGED
    val active = status.session == SessionLifecycle.ACTIVE && !changed && !status.contact.blocked && !status.contact.request
    val list = rememberLazyListState()
    LaunchedEffect(state.messages.size) { if (state.messages.isNotEmpty()) list.animateScrollToItem(state.messages.lastIndex) }
    Column(Modifier.fillMaxSize().imePadding()) {
        PageHeader(status.contact.displayName, subtitle = when {
            status.contact.blocked -> "Blocked on this device"
            changed -> "! Security identity changed"
            status.contact.request -> "Message request - Unverified"
            !active -> "Session unavailable"
            else -> null
        }, back = back, avatarName = status.contact.displayName) {
            HeaderAction(Glyph.SHIELD, "Security", security)
            Box {
                HeaderAction(Glyph.MORE, "Conversation options") { actions = true }
                DropdownMenu(expanded = actions, onDismissRequest = { actions = false }) {
                    if (state.networkConfigured && !state.demo)
                        DropdownMenuItem(text = { Text("Sync") }, onClick = { actions = false; sync() })
                    DropdownMenuItem(text = { Text("Clear conversation") }, onClick = { actions = false; clearing = true })
                    if (state.networkConfigured && !state.demo)
                        DropdownMenuItem(text = { Text("Disappearing messages · ${DisappearingTimer.from(state.disappearingPolicies[status.contact.remoteDeviceId] ?: 0).label}") },
                            enabled = active && !state.loading, onClick = { actions = false; timerSelector = true })
                }
            }
        }
        if(!state.networkConnected) Box(Modifier.padding(horizontal = GhostLayout.pageInset)) { NetworkActions(state, connect, sync) }
        if (state.demo) Text("LOCAL SIMULATOR · Replies are generated by the debug endpoint", Modifier.padding(GhostLayout.pageInset),
            style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.primary)
        if (changed) TextButton(onClick = security, modifier = Modifier.fillMaxWidth()) { Text("! Review changed identity before sending", color = MaterialTheme.colorScheme.error) }
        LazyColumn(Modifier.weight(1f).fillMaxWidth(), state = list, contentPadding = PaddingValues(horizontal = GhostLayout.pageInset, vertical = GhostLayout.dividerGap), verticalArrangement = Arrangement.spacedBy(GhostDimensions.compact)) {
            if (state.messages.isEmpty()) item { InfoPanel("A conversation starts here", if (state.networkConfigured && !state.demo) "End-to-end encrypted. Messages arrive automatically while Ghost Cloak is open." else "Messages are encrypted before local transport. This prototype cannot deliver to another device over a network.") }
            itemsIndexed(state.messages, key = { _, message -> message.localId }) { index, message ->
                val date = Instant.ofEpochMilli(message.timestamp).atZone(ZoneId.systemDefault()).toLocalDate()
                val previous = state.messages.getOrNull(index-1)?.let { Instant.ofEpochMilli(it.timestamp).atZone(ZoneId.systemDefault()).toLocalDate() }
                Column(verticalArrangement=Arrangement.spacedBy(GhostDimensions.medium)) {
                    if(date!=previous) Box(Modifier.fillMaxWidth().padding(vertical=GhostDimensions.medium),contentAlignment=Alignment.Center) {
                        Surface(shape=RoundedCornerShape(GhostDimensions.medium),color=MaterialTheme.colorScheme.surface) {
                            Text(when(date) {LocalDate.now()->"Today"; LocalDate.now().minusDays(1)->"Yesterday"; else->date.format(DateTimeFormatter.ofPattern("MMM d, yyyy"))},
                                Modifier.padding(horizontal=GhostDimensions.medium,vertical=GhostDimensions.tight),style=MaterialTheme.typography.labelSmall,color=MaterialTheme.colorScheme.onSurfaceVariant)
                        }
                    }
                    if (message.policyEvent) Column(Modifier.fillMaxWidth().padding(GhostDimensions.medium), horizontalAlignment = Alignment.CenterHorizontally) {
                        Text(message.body, style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.onSurfaceVariant,
                            textAlign = androidx.compose.ui.text.style.TextAlign.Center)
                        if (message.direction == Direction.OUTGOING && message.state in setOf(MessageState.PENDING, MessageState.FAILED))
                            Text(if (message.state == MessageState.PENDING) "Update pending · applies locally" else "Update not delivered · choose the timer again to retry",
                                style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                    else if(message.attachment!=null) MessageBubble(message,onDelete={deleting=message.localId}) {
                        AttachmentMessage(message,active,message.localId in state.cachedAttachments,refresh)
                    } else MessageBubble(message,onDelete={deleting=message.localId})
                }
            }
        }
        if (status.contact.request && !status.contact.blocked) {
            Column(Modifier.padding(GhostLayout.pageInset), verticalArrangement = Arrangement.spacedBy(GhostDimensions.compact)) {
                Text("Accept this conversation?", style = MaterialTheme.typography.titleMedium)
                Text("This sender is not in your contacts. Accepting lets you reply; it does not verify their identity.", style = MaterialTheme.typography.bodyMedium)
                Row(horizontalArrangement = Arrangement.spacedBy(GhostDimensions.medium)) {
                    Button(onClick = accept, enabled = !state.loading) { Text("Accept") }
                    TextButton(onClick = reject, enabled = !state.loading) { Text("Block & delete") }
                }
            }
        }
        Surface(color=MaterialTheme.colorScheme.surface) { Column(Modifier.padding(horizontal = GhostLayout.pageInset, vertical=GhostDimensions.controlGap), verticalArrangement = Arrangement.spacedBy(GhostDimensions.compact)) {
            ErrorNotice(state.error, important = state.errorImportant)
            if (size > ConversationPayload.MAX_TEXT || rejectedPaste) Text("Too large. Maximum 16,368 UTF-8 bytes; text was not sent.", color = MaterialTheme.colorScheme.error)
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(GhostDimensions.controlGap)) {
                if(state.networkConfigured && !state.demo) AttachmentComposer(status.contact.remoteDeviceId,active && !state.loading,refresh)
                OutlinedTextField(draft, onValueChange = { rejectedPaste = it.length > 65536; if (!rejectedPaste) draft = it },
                    enabled = active && !state.loading, modifier = Modifier.weight(1f), placeholder = { Text("Write a message…") }, maxLines = 5,
                    colors=OutlinedTextFieldDefaults.colors(unfocusedBorderColor=androidx.compose.ui.graphics.Color.Transparent,unfocusedContainerColor=MaterialTheme.colorScheme.surface,focusedContainerColor=MaterialTheme.colorScheme.surface),
                    shape = RoundedCornerShape(GhostDimensions.spacious), isError = size > ConversationPayload.MAX_TEXT)
                FilledIconButton(onClick = { send(draft) { draft = "" } }, enabled = active && !state.loading && draft.isNotBlank() && size <= ConversationPayload.MAX_TEXT && !rejectedPaste,
                    modifier = Modifier.size(GhostDimensions.avatar)) { AppIcon(Glyph.SEND,"Send") }
            }
            Text(if (size > 14000) "$size / 16,368 bytes" else "End-to-end encrypted", Modifier.padding(start = GhostDimensions.controlGap, bottom = GhostDimensions.medium), style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
        }
    }
    }
    deleting?.let { id -> AlertDialog(onDismissRequest = { deleting = null }, title = { Text("Delete message?") },
        text = { Text("This removes the message from this device only.") },
        confirmButton = { TextButton(onClick = { deleting = null; delete(id) }) { Text("Delete") } },
        dismissButton = { TextButton(onClick = { deleting = null }) { Text("Cancel") } }) }
    if (clearing) AlertDialog(onDismissRequest = { clearing = false }, title = { Text("Clear conversation?") },
        text = { Text("This removes all messages with this contact from this device. The contact will remain.") },
        confirmButton = { TextButton(onClick = { clearing = false; clear() }) { Text("Clear") } },
        dismissButton = { TextButton(onClick = { clearing = false }) { Text("Cancel") } })
    if (timerSelector) AlertDialog(onDismissRequest = { timerSelector = false }, title = { Text("Disappearing messages") },
        text = { Column {
            Text("Both devices need disappearing-message support. Applies to future messages. Your timer starts when their delivery ACK is observed; theirs starts when received and saved, not when read. Queued messages have no countdown.", style = MaterialTheme.typography.bodySmall)
            DisappearingTimer.entries.forEach { timer ->
                TextButton(onClick = { timerSelector = false; disappearing(timer.seconds) }, modifier = Modifier.fillMaxWidth()) {
                    Text(if (timer.seconds == (state.disappearingPolicies[status.contact.remoteDeviceId] ?: 0)) "${timer.label} ✓" else timer.label)
                }
            }
        } }, confirmButton = {}, dismissButton = { TextButton(onClick = { timerSelector = false }) { Text("Cancel") } })
}
